import type { Metadata } from 'next';
import './globals.css';
<<<<<<< HEAD
import {Toaster} from '@/components/ui/toaster';
import {Dosis} from 'next/font/google';

const dosis = Dosis({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'FinEye',
  description: 'Generated by Firebase Studio',
=======
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'FinanceFlow',
  description: 'Your personal finance manager',
>>>>>>> 61ae0a6 (Initial prototype)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
<<<<<<< HEAD
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Dosis:wght@200..800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${dosis.className} antialiased`}>
=======
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Dosis:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className="font-body antialiased">
>>>>>>> 61ae0a6 (Initial prototype)
        {children}
        <Toaster />
      </body>
    </html>
  );
}
